Repository NeuroML/pyNeuroML, pull requests merged in 2021-12, with the labels that each got.

#134 feat(pynml): add `-moose` option
  man/man1/pynml.1
  pyneuroml/pynml.py
  test-ghactions.sh
Labels: T: enhancement, S: ready for review

#157 Tweaks to tuner code
  README.md
  pyneuroml/povray/NeuroML2ToPOVRay.py
  pyneuroml/pynml.py
  pyneuroml/tune/NeuroMLController.py
  pyneuroml/tune/NeuroMLSimulation.py
  pyneuroml/tune/NeuroMLTuner.py
  requirements-dev.txt
  setup.py
Labels: T: bug, S: ready for review

#158 Specifying universal_newlines so "realtime output" works correctly
  pyneuroml/pynml.py
  tests/test_pynml.py
Labels: T: bug, T: enhancement

#159 Feat/document 2stage opt
  pyneuroml/tune/NeuroMLTuner.py
Labels: T: enhancement, S: ready for review
