Repository NeuroML/pyNeuroML, pull requests merged in 2023-11, with the labels that each got.

#270 feat(graph-generator): allow passing kwargs to GraphVizHandler
  pyneuroml/pynml.py
Labels: T: enhancement, S: ready for review

#271 feat(plotter): use matplotlib rcparams defaults for missing options
  pyneuroml/plot/Plot.py
  pyneuroml/plot/PlotSpikes.py
Labels: T: enhancement

#266 added -validate-sbml option
  examples/test_data/valid_doc.sbml
  pyneuroml/pynml.py
  pyneuroml/sbml/__init__.py
  setup.cfg
  test-ghactions.sh
  tests/sbml/test_data/inconsistent_units_doc.sbml
  tests/sbml/test_data/invalid_doc00.sbml
  tests/sbml/test_data/invalid_doc01.sbml
  tests/sbml/test_data/invalid_doc02.sbml
  tests/sbml/test_data/no_read_access.sbml
  tests/sbml/test_data/valid_doc.sbml
  tests/sbml/test_sbml.py
Labels: T: enhancement, S: ready for review

#262 Expose `meta` in LEMSSimulation
  pyneuroml/lems/LEMSSimulation.py
  pyneuroml/lems/LEMS_TEMPLATE.xml
  tests/lems/test_lemssimulation.py
Labels: T: enhancement, S: ready for review

#280 fix(nsgr-netpyne): include model files in NSG zip also
  pyneuroml/nsgr/__init__.py
Labels: T: bug, S: ready for review
