Repository NeuroML/pyNeuroML, pull requests merged in 2024-05, with the labels that each got.

#361 feat(rotation): allow users to pick if they want a copy
  pyneuroml/utils/__init__.py
Labels: S: ready for review

#348 animate matplotlib plots
  pyneuroml/plot/Plot.py
  tests/plot/test_plot.py
Labels: T: enhancement

#352 feat(pynml-modchananalysis): add labels and fix file name
  pyneuroml/analysis/NML2ChannelAnalysis.py
  pyneuroml/neuron/analysis/HHanalyse.py
  pyneuroml/utils/__init__.py
Labels: T: enhancement

#354 Annotations: completes exporting and extraction of annotations that we use in NeuroML
  .pre-commit-config.yaml
  pyneuroml/annotations.py
  pyneuroml/utils/xml.py
  tests/test_annotations.py
  tests/test_biosimulations.py
Labels: T: enhancement

#371 chore: improve contributing documentation
  CONTRIBUTING.md
Labels: C: docs
